// AUTO-GENERATED by gen-manifest.ts — do not edit manually.
// Source: volcengine.models.json (offline-prepared from LiteLLM + Ark endpoints)
// Used by endpointToModel() to enrich live Ark endpoints with pricing / context
// / capability data without loading any JSON at runtime.

export interface ModelData {
    contextWindow: number;
    maxTokens: number;
    reasoning: boolean;
    vision: boolean;
    cost: {
        input: number;
        output: number;
        cacheRead: number;
        cacheWrite: number;
        tiers?: { inputTokensAbove: number; input: number; output: number; cacheRead: number; cacheWrite: number }[];
    };
}

export const MODEL_DATA: Record<string, ModelData> = {
    "deepseek-v4-pro-ga(260813)": {
        contextWindow: 1000000,
        maxTokens: 393216,
        reasoning: true,
        vision: false,
        cost: { input: 1.32, output: 3.9600000000000004, cacheRead: 0, cacheWrite: 0 },
    },
    "deepseek-v4-flash-ga(260731)": {
        contextWindow: 1000000,
        maxTokens: 393216,
        reasoning: true,
        vision: false,
        cost: { input: 0.44, output: 1.32, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-2-1-turbo(260628)": {
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        vision: true,
        cost: { input: 0.087, output: 0.52, cacheRead: 0, cacheWrite: 0, tiers: [{ inputTokensAbove: 32000, input: 0.13, output: 0.78, cacheRead: 0, cacheWrite: 0 }, { inputTokensAbove: 128000, input: 0.26, output: 1.5999999999999999, cacheRead: 0, cacheWrite: 0 }] },
    },
    "glm-5-2(260617)": {
        contextWindow: 1048576,
        maxTokens: 131072,
        reasoning: true,
        vision: false,
        cost: { input: 1.4, output: 4.4, cacheRead: 0, cacheWrite: 0 },
    },
    "deepseek-v4-pro(260425)": {
        contextWindow: 1000000,
        maxTokens: 393216,
        reasoning: true,
        vision: false,
        cost: { input: 1.32, output: 3.9600000000000004, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-2-0-pro(260215)": {
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        vision: true,
        cost: { input: 0.45999999999999996, output: 2.3, cacheRead: 0, cacheWrite: 0, tiers: [{ inputTokensAbove: 32000, input: 0.7, output: 3.5, cacheRead: 0, cacheWrite: 0 }, { inputTokensAbove: 128000, input: 1.4, output: 7, cacheRead: 0, cacheWrite: 0 }] },
    },
    "glm-4-7(251222)": {
        contextWindow: 204800,
        maxTokens: 131072,
        reasoning: true,
        vision: false,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-1-8(251228)": {
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-1-6(251015)": {
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-1-5-pro-32k(250115)": {
        contextWindow: 32768,
        maxTokens: 8192,
        reasoning: false,
        vision: false,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "deepseek-v3(250324)": {
        contextWindow: 65536,
        maxTokens: 8192,
        reasoning: false,
        vision: false,
        cost: { input: 0.27, output: 1.1, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-2-1-pro(260628)": {
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-evolving(latest-version)": {
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "deepseek-v4-flash(260425)": {
        contextWindow: 1000000,
        maxTokens: 393216,
        reasoning: true,
        vision: false,
        cost: { input: 0.44, output: 1.32, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-code(preview-251028)": {
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-1-6-vision(250815)": {
        contextWindow: 128000,
        maxTokens: 16384,
        reasoning: false,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    "doubao-seed-1-6(250615)": {
        contextWindow: 256000,
        maxTokens: 128000,
        reasoning: true,
        vision: true,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
};
